CREATE TABLE "GCG_3536_SLOW_DEAD"(
 "BIRUNID" BIGINT NOT NULL ,
 "PART" VARCHAR(20),
 "LOCATION" VARCHAR(2),
 "DATE_HISTORY" DATE,
 "CODE_TRANSACTION" VARCHAR(3),
 "TRANSACTION_DESC" VARCHAR(15),
 "DESCRIPTION" VARCHAR(50),
 "QTY_ONHAND" NUMERIC(12,4),
 "AMT_COST" NUMERIC(12,4),
 "TYPE" VARCHAR(6));
